# Generated by Django 5.2.5 on 2025-12-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food99api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
