# Generated by Django 5.2.5 on 2026-02-26 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food99api', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
