# Generated by Django 5.2.5 on 2025-09-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food99api', '0003_menuvariant_menuitem_variant_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food99api.menuitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food99api.menuvariant')),
            ],
            options={
                'unique_together': {('menu_item', 'variant')},
            },
        ),
    ]
