# Generated by Django 5.2.5 on 2025-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food99api', '0003_buyerprofile_description_buyerprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
