# Generated by Django 5.2.5 on 2026-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food99api', '0004_otp_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
